### ISSUE TITLE
dataversion field

### ISSUE THREAD

**Issue by exploide** [ENT8R/oneway-data-api#12]
It came to my mind that it could be useful to include information about the data version in the response. So you and others and quickly see if the served data is up to date without monitoring the log of the cron job. Something like

```json
{
    "dataversion": "20180419",
    "segments": []
}
```

This also would do that "remember when updated the last time" thing you wished for (though, without the blocking access intention behind it).

@westnordost would you consider this useful? I could implement that.

**Comment by westnordost** [comment]
I wouldn't consider it useful.

I am informed about any error that happens on the scheduled job

Am 19. April 2018 09:55:03 MESZ schrieb Jannik Vieten <notifications@github.com>:
>It came to my mind that it could be useful to include information about
>the data version in the response. So you and others and quickly see if
>the served data is up to date without monitoring the log of the cron
>job. Something like
>
>```json
>{
>    "dataversion": "20180419",
>    "segments": []
>}
>```
>
>This also would do that "remember when updated the last time" thing you
>wished for (though, without the blocking access intention behind it).
>
>@westnordost would you consider this useful? I could implement that.

**Comment by exploide** [comment]
ok
