### ISSUE TITLE
404 on https://grab.community.improve-osm.org/dumps/

### ISSUE THREAD

**Issue by westnordost** [ENT8R/oneway-data-api#19]
Seems to be gone now. I contacted @jinalfoflia on OSM slack about it. But maybe she will also read this here.

**Comment by ENT8R** [comment]
https://grab.community.improve-osm.org/dumps/
works again

**Comment by westnordost** [comment]
Right, forgot to close this. In the meantime, their SSL certificate expired, too, but they fixed it after I noticed them about it. All in all, they don't seem to pay that much attention to it. Sooner or later, that quest type might need to be dropped.
